/**
 * Server-only creative (visual) generation for the Content Studio.
 *
 * Flow per creative: load the content item under the caller's RLS -> load the
 * brand profile, visual brand profile and the client's reference images ->
 * build a structured, variation-specific visual prompt -> call the image
 * provider with the reference images attached -> upload the bytes to the
 * private `creatives` bucket -> record the versioned asset row.
 *
 * Each of the four creatives is generated by its own call, so they are four
 * independent assets with independent versions — never a collage.
 * The provider key never leaves this module.
 */
import { generateImage, ImageGenerationError, type ReferenceImage } from "@/lib/ai/image.server";
import { renderBrandContext, type BrandContext } from "@/lib/brand/context";
import {
  renderVisualConfig,
  toVisualConfig,
  type BrandVisualConfig,
} from "@/lib/brand/visual-schema";
import {
  CREATIVE_VARIANTS,
  GENERIC_OUTPUT_BANLIST,
  variantByIndex,
  type CreativeAssetType,
  type CreativeVariant,
} from "@/lib/content/creative-variants";
import {
  PLATFORMS,
  creativeFormatById,
  defaultFormatFor,
  toCreativePrompt,
  type CreativePrompt,
} from "@/lib/content/schema";

export const CREATIVES_BUCKET = "creatives";
export const REFERENCES_BUCKET = "brand-references";
/** Providers cap inline images; a focused set guides better than a long tail. */
const MAX_REFERENCES_PER_REQUEST = 4;

type QueryResult<T> = Promise<{ data: T; error: unknown }>;

type SupabaseLike = {
  from: (table: string) => any;
  storage: {
    from: (bucket: string) => {
      upload: (
        path: string,
        body: ArrayBuffer | Uint8Array | Blob,
        options?: Record<string, unknown>,
      ) => QueryResult<unknown>;
      download: (path: string) => QueryResult<Blob | null>;
      remove: (paths: string[]) => QueryResult<unknown>;
    };
  };
};

export type LoadedContentItem = {
  id: string;
  workspace_id: string;
  client_id: string;
  platform: string;
  title: string | null;
  hook: string | null;
  body: string | null;
  cta: string | null;
  creative_prompt: unknown;
};

/** Loads the content item with the caller's RLS-scoped client. */
export async function loadContentItem(
  supabase: unknown,
  contentItemId: string,
): Promise<LoadedContentItem | null> {
  const db = supabase as SupabaseLike;
  const { data, error } = await db
    .from("content_items")
    .select("id, workspace_id, client_id, platform, title, hook, body, cta, creative_prompt")
    .eq("id", contentItemId)
    .maybeSingle();
  if (error || !data) return null;
  return data as LoadedContentItem;
}

export type LoadedReference = {
  storagePath: string;
  description: string | null;
  image: ReferenceImage;
};

function toBase64(bytes: Uint8Array): string {
  let binary = "";
  const chunk = 0x8000;
  for (let index = 0; index < bytes.length; index += chunk) {
    binary += String.fromCharCode(...bytes.subarray(index, index + chunk));
  }
  return btoa(binary);
}

/**
 * Loads the client's reference images: rows through the caller's RLS, bytes
 * through the service-role client because the bucket is private.
 */
export async function loadReferenceImages(args: {
  supabase: unknown;
  admin: unknown;
  clientId: string;
}): Promise<LoadedReference[]> {
  const db = args.supabase as SupabaseLike;
  const { data, error } = await db
    .from("client_brand_references")
    .select("storage_path, description, mime_type")
    .eq("client_id", args.clientId)
    .order("created_at", { ascending: false })
    .limit(MAX_REFERENCES_PER_REQUEST);

  if (error) {
    console.error("[creative] reference rows unavailable", error);
    return [];
  }

  const rows = (data ?? []) as Array<{
    storage_path: string;
    description: string | null;
    mime_type: string | null;
  }>;

  const loaded: LoadedReference[] = [];
  for (const row of rows) {
    try {
      const download = await (args.admin as SupabaseLike).storage
        .from(REFERENCES_BUCKET)
        .download(row.storage_path);
      if (download.error || !download.data) {
        console.error("[creative] reference download failed", row.storage_path, download.error);
        continue;
      }
      const buffer = await (download.data as Blob).arrayBuffer();
      if (buffer.byteLength === 0) continue;
      loaded.push({
        storagePath: row.storage_path,
        description: row.description,
        image: {
          base64: toBase64(new Uint8Array(buffer)),
          mimeType: row.mime_type ?? "image/png",
        },
      });
    } catch (error) {
      console.error("[creative] reference unreadable", row.storage_path, error);
    }
  }
  return loaded;
}

/**
 * The creative prompt engine. Combines brand identity, the visual brand
 * profile, reference context, the content being published and the variant's
 * own direction into one self-contained instruction.
 */
export function composeVariantPrompt(args: {
  creative: CreativePrompt;
  brand: BrandContext | null;
  visual: BrandVisualConfig;
  references: LoadedReference[];
  variant: CreativeVariant;
  content: { title: string | null; hook: string | null; body: string | null; cta: string | null };
  platformLabel: string;
  aspectRatio: string;
}): string {
  const { creative, variant, visual } = args;
  const brandText = args.brand ? renderBrandContext(args.brand).slice(0, 1800) : "";
  const visualText = renderVisualConfig(visual).slice(0, 1600);

  const referenceLines = args.references.map((reference, index) =>
    reference.description?.trim()
      ? `Reference ${index + 1}: ${reference.description.trim()}`
      : `Reference ${index + 1}: use for visual language, colour, lighting and composition.`,
  );

  const negatives = [creative.negative_prompt?.trim(), GENERIC_OUTPUT_BANLIST]
    .filter(Boolean)
    .join("; ");

  return [
    `Produce ONE single finished social media creative image — creative ${variant.index} of 4 for this post.`,
    "It must be one complete standalone image. Never a collage, grid, mosaic, split panel, multi-frame layout or mockup sheet.",
    "",
    `=== THIS CREATIVE'S ANGLE: ${variant.label.toUpperCase()} ===`,
    variant.direction,
    `It must be clearly and visibly different from the other three angles (${CREATIVE_VARIANTS.filter((entry) => entry.index !== variant.index)
      .map((entry) => entry.label)
      .join(", ")}) in subject, framing and treatment — while staying the same brand.`,
    "",
    "=== CREATIVE BRIEF FOR THIS POST ===",
    creative.prompt?.trim() ? creative.prompt.trim() : "",
    creative.subject ? `Subject: ${creative.subject}` : "",
    creative.composition ? `Composition & framing: ${creative.composition}` : "",
    creative.visual_style ? `Visual style: ${creative.visual_style}` : "",
    creative.environment ? `Environment / setting: ${creative.environment}` : "",
    creative.mood ? `Mood & lighting: ${creative.mood}` : "",
    creative.typography ? `On-image text direction: ${creative.typography}` : "No on-image text.",
    creative.brand_considerations ? `Brand considerations: ${creative.brand_considerations}` : "",
    "",
    visualText
      ? `=== VISUAL BRAND PROFILE (these rules override generic style choices) ===\n${visualText}`
      : "",
    "",
    args.references.length > 0
      ? [
          `=== REFERENCE IMAGES (${args.references.length} attached — study them first) ===`,
          "The attached images are the brand's own visual references. Match their visual language: composition habits, colour palette, lighting quality, texture, materials, level of realism and overall mood.",
          "Do not copy them literally, do not reproduce any recognisable person, product label or text from them, and do not place them inside the output.",
          ...referenceLines,
        ].join("\n")
      : "No reference images are attached — follow the visual brand profile strictly instead of defaulting to stock-style imagery.",
    "",
    brandText ? `=== BRAND IDENTITY ===\n${brandText}` : "",
    "",
    "=== CONTENT THIS VISUAL ACCOMPANIES ===",
    args.content.title ? `Post concept: ${args.content.title}` : "",
    args.content.hook ? `Hook: ${args.content.hook}` : "",
    args.content.body ? `Caption context: ${args.content.body.slice(0, 700)}` : "",
    args.content.cta ? `Call to action: ${args.content.cta}` : "",
    "",
    "=== OUTPUT REQUIREMENTS ===",
    `Destination platform: ${args.platformLabel}.`,
    `Aspect ratio: exactly ${args.aspectRatio} — compose natively for this frame with safe margins. Do not stretch, letterbox or crop a different ratio into it.`,
    "Photographic realism and material detail unless the visual brand profile asks otherwise. Production-ready quality.",
    `Never produce: ${negatives}.`,
  ]
    .filter((line) => line !== "")
    .join("\n");
}

export type CreativeAssetRecord = {
  id: string;
  version: number;
  variantIndex: number;
  variantLabel: string | null;
  concept: string | null;
  assetType: CreativeAssetType;
  status: string;
  storagePath: string | null;
  provider: string | null;
  model: string | null;
  aspectRatio: string | null;
  formatId: string | null;
  mimeType: string | null;
  byteSize: number | null;
  createdAt: string;
};

export type GenerateCreativeResult =
  | { ok: true; asset: CreativeAssetRecord }
  | { ok: false; code: string; message: string; retryable: boolean; variantIndex?: number };

/**
 * Generates ONE creative variant for a content item and stores it durably.
 * Versions are tracked per variant, so regenerating creative #2 never touches
 * creatives #1, #3 or #4 and never destroys earlier versions.
 */
export async function generateCreativeVariant(args: {
  /** Caller's RLS-scoped client — used for every table read/write. */
  supabase: unknown;
  /** Service-role client — used only for the private buckets. */
  admin: unknown;
  userId: string;
  contentItemId: string;
  variantIndex: number;
  formatId?: string | null;
  promptOverride?: string | null;
}): Promise<GenerateCreativeResult> {
  const db = args.supabase as SupabaseLike;
  const variant = variantByIndex(args.variantIndex) ?? CREATIVE_VARIANTS[0]!;

  const item = await loadContentItem(args.supabase, args.contentItemId);
  if (!item) {
    return {
      ok: false,
      code: "forbidden",
      message: "This content is not available in your workspace.",
      retryable: false,
      variantIndex: variant.index,
    };
  }

  const creative = toCreativePrompt(item.creative_prompt);
  if (!creative.prompt.trim() && !args.promptOverride?.trim()) {
    return {
      ok: false,
      code: "missing_prompt",
      message: "Generate the creative direction first — the visual needs a creative brief.",
      retryable: false,
      variantIndex: variant.index,
    };
  }

  const format =
    creativeFormatById(args.formatId) ?? creativeFormatById(defaultFormatFor(item.platform));
  const aspectRatio = format?.aspectRatio ?? creative.aspect_ratio ?? "1:1";
  const platformLabel =
    PLATFORMS.find((entry) => entry.id === item.platform)?.label ?? item.platform;

  // Brand + visual context sharpen the visual; a missing profile must not block generation.
  let brand: BrandContext | null = null;
  let visual: BrandVisualConfig = toVisualConfig(null);
  try {
    const { data } = await db
      .from("client_brand_profiles")
      .select("*")
      .eq("client_id", item.client_id)
      .maybeSingle();
    if (data) {
      const { buildBrandContext } = await import("@/lib/brand/context");
      brand = buildBrandContext(data as Record<string, unknown>);
      visual = toVisualConfig((data as Record<string, unknown>)["visual_config"]);
    }
  } catch (error) {
    console.error("[creative] brand context unavailable", error);
  }

  const references = await loadReferenceImages({
    supabase: args.supabase,
    admin: args.admin,
    clientId: item.client_id,
  });

  const prompt =
    args.promptOverride?.trim() ||
    composeVariantPrompt({
      creative,
      brand,
      visual,
      references,
      variant,
      content: { title: item.title, hook: item.hook, body: item.body, cta: item.cta },
      platformLabel,
      aspectRatio,
    });

  const nextVersion = await nextVersionFor(db, item.id, variant.index);

  const { data: created, error: insertError } = await db
    .from("content_creatives")
    .insert({
      workspace_id: item.workspace_id,
      client_id: item.client_id,
      content_item_id: item.id,
      created_by: args.userId,
      version: nextVersion,
      variant_index: variant.index,
      variant_label: variant.label,
      concept: variant.summary,
      asset_type: "image",
      status: "pending",
      prompt,
      prompt_reference: creative as unknown as Record<string, unknown>,
      reference_paths: references.map((reference) => reference.storagePath),
      format_id: format?.id ?? null,
      aspect_ratio: aspectRatio,
      storage_bucket: CREATIVES_BUCKET,
    })
    .select("*")
    .single();

  if (insertError || !created) {
    console.error("[creative] could not create asset row", insertError);
    return {
      ok: false,
      code: "db_error",
      message: "Couldn't start the creative generation. Please try again.",
      retryable: true,
      variantIndex: variant.index,
    };
  }

  const row = created as Record<string, unknown>;
  const assetId = String(row["id"]);

  try {
    const image = await generateImage({
      prompt,
      negativePrompt: creative.negative_prompt,
      aspectRatio,
      referenceImages: references.map((reference) => reference.image),
    });

    const extension = image.mimeType.includes("jpeg")
      ? "jpg"
      : image.mimeType.includes("webp")
        ? "webp"
        : "png";
    const storagePath = `${item.workspace_id}/${item.client_id}/${item.id}/${assetId}.${extension}`;

    const upload = await (args.admin as SupabaseLike).storage
      .from(CREATIVES_BUCKET)
      .upload(storagePath, image.bytes, { contentType: image.mimeType, upsert: true });

    if (upload.error) {
      console.error("[creative] upload failed", upload.error);
      throw new ImageGenerationError(
        "image_failed",
        "The image was generated but could not be stored. Please try again.",
        true,
      );
    }

    const { data: updated } = await db
      .from("content_creatives")
      .update({
        status: "succeeded",
        storage_path: storagePath,
        mime_type: image.mimeType,
        byte_size: image.bytes.byteLength,
        provider: image.provider,
        model: image.model,
      })
      .eq("id", assetId)
      .select("*")
      .single();

    await recordUsage(db, {
      workspaceId: item.workspace_id,
      clientId: item.client_id,
      contentItemId: item.id,
      userId: args.userId,
      status: "success",
      provider: image.provider,
      model: image.model,
      durationMs: image.durationMs,
    });

    await db
      .from("content_items")
      .update({ status: "creative_generated" })
      .eq("id", item.id)
      .in("status", ["draft", "ready_for_creative", "generating_creative"]);

    return { ok: true, asset: mapAsset((updated as Record<string, unknown>) ?? { ...row, id: assetId }) };
  } catch (error) {
    const isImageError = error instanceof ImageGenerationError;
    const code = isImageError ? error.code : "image_failed";
    const message =
      error instanceof Error ? error.message : "Creative generation failed. Please try again.";
    const retryable = isImageError ? error.retryable : true;
    console.error("[creative] generation failed", { code, message, variant: variant.index });

    await db
      .from("content_creatives")
      .update({ status: "failed", error_code: code, error_message: message.slice(0, 500) })
      .eq("id", assetId);

    await recordUsage(db, {
      workspaceId: item.workspace_id,
      clientId: item.client_id,
      contentItemId: item.id,
      userId: args.userId,
      status: "error",
      errorCode: code,
    });

    return { ok: false, code, message, retryable, variantIndex: variant.index };
  }
}

async function nextVersionFor(
  db: SupabaseLike,
  contentItemId: string,
  variantIndex: number,
): Promise<number> {
  const { data } = await db
    .from("content_creatives")
    .select("version")
    .eq("content_item_id", contentItemId)
    .eq("variant_index", variantIndex)
    .order("version", { ascending: false })
    .limit(1);
  const rows = (data ?? []) as Array<{ version: number | null }>;
  return (rows[0]?.version ?? 0) + 1;
}

export function mapAsset(row: Record<string, unknown>): CreativeAssetRecord {
  return {
    id: String(row["id"]),
    version: Number(row["version"] ?? 1),
    variantIndex: Number(row["variant_index"] ?? 1),
    variantLabel: (row["variant_label"] as string | null) ?? null,
    concept: (row["concept"] as string | null) ?? null,
    assetType: ((row["asset_type"] as string | null) ?? "image") as CreativeAssetType,
    status: String(row["status"] ?? "pending"),
    storagePath: (row["storage_path"] as string | null) ?? null,
    provider: (row["provider"] as string | null) ?? null,
    model: (row["model"] as string | null) ?? null,
    aspectRatio: (row["aspect_ratio"] as string | null) ?? null,
    formatId: (row["format_id"] as string | null) ?? null,
    mimeType: (row["mime_type"] as string | null) ?? null,
    byteSize: (row["byte_size"] as number | null) ?? null,
    createdAt: String(row["created_at"] ?? new Date().toISOString()),
  };
}

async function recordUsage(
  db: SupabaseLike,
  values: {
    workspaceId: string;
    clientId: string;
    contentItemId: string;
    userId: string;
    status: "success" | "error";
    provider?: string;
    model?: string;
    errorCode?: string;
    durationMs?: number;
  },
): Promise<void> {
  const { error } = await db.from("ai_generation_events").insert({
    workspace_id: values.workspaceId,
    client_id: values.clientId,
    content_item_id: values.contentItemId,
    user_id: values.userId,
    generation_type: "creative_image",
    status: values.status,
    provider: values.provider ?? null,
    model: values.model ?? null,
    error_code: values.errorCode ?? null,
    duration_ms: values.durationMs ?? null,
  });
  if (error) console.error("[creative] usage log failed", error);
}
